name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build with Docker Compose
      run: |
        cd docker
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
